SET SESSION DATABASE GDEV1T_GCFR;

CREATE MULTISET TABLE EXEC_LOGS ,FALLBACK ,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    MAP = TD_MAP1
    (
    RUN_ID BIGINT NOT NULL,
    LOAD_ID VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
    SOURCE_NAME VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL  default user,
    TABLE_NAME VARCHAR(130) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
    SQL_SCRIPT_SEQ INTEGER NOT NULL,
    SQL_SCRIPT CLOB CHARACTER SET LATIN NOT NULL,
    START_TIMESTAMP TIMESTAMP(6) NOT NULL,
    END_TIMESTAMP TIMESTAMP(6) NOT NULL,
    ERROR_CODE INTEGER,
    ERROR_MSG VARCHAR(1000) CHARACTER SET LATIN NOT CASESPECIFIC,
    ROWS_COUNT FLOAT,
    CREATED_BY VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL  default user)
    PRIMARY INDEX ( RUN_ID );