DELETE DATABASE GDEV1_ETL ALL;
DROP DATABASE GDEV1_ETL;

DELETE DATABASE STG_ONLINE ALL;
DROP DATABASE STG_ONLINE;

DELETE DATABASE GDEV1V_STG_ONLINE ALL;
DROP DATABASE GDEV1V_STG_ONLINE;

DELETE DATABASE GDEV1T_STG ALL;
DROP DATABASE GDEV1T_STG;

DELETE DATABASE GDEV1V_STG ALL;
DROP DATABASE GDEV1V_STG;

DELETE DATABASE GDEV1V_INP ALL;
DROP DATABASE GDEV1V_INP;

DELETE DATABASE GDEV1T_UTLFW ALL;
DROP DATABASE GDEV1T_UTLFW;

DELETE DATABASE GDEV1V_UTLFW ALL;
DROP DATABASE GDEV1V_UTLFW;

DELETE DATABASE GDEV1T_SRCI ALL;
DROP DATABASE GDEV1T_SRCI;

DELETE DATABASE GDEV1V_SRCI ALL;
DROP DATABASE GDEV1V_SRCI;

DELETE DATABASE GDEV1T_BASE ALL;
DROP DATABASE GDEV1T_BASE;

DELETE DATABASE GDEV1V_BASE ALL;
DROP DATABASE GDEV1V_BASE;

DELETE DATABASE GDEV1_EDWH ALL;
DROP DATABASE GDEV1_EDWH;

