REPLACE PROCEDURE /*VER.1*/ GDEV1P_PP.COUNT_ROWS 
(
	in I_DB 			VARCHAR (200),
	in I_TBL 			VARCHAR (200),
	out O_CNT 			FLOAT,
	out O_RETURN_CODE 	INTEGER,
	out O_RETURN_MSG 	VARCHAR (5000)
)
BEGIN
	
	DECLARE C1 CURSOR FOR S1;
	BEGIN
		DECLARE V_TABLE_NAME 	VARCHAR(1000) DEFAULT '';
		DECLARE v_cnt_query 	VARCHAR(1000);
		DECLARE v_cnt_result 	FLOAT DEFAULT 0;
		
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			SET O_CNT = 0;
			SET O_RETURN_CODE = SQLCODE;
			GET DIAGNOSTICS EXCEPTION 1 O_RETURN_MSG = MESSAGE_TEXT;
		END;
		
		IF COALESCE (I_TBL, '') <>'' 
		THEN
			IF COALESCE (I_DB, '') <>'' 
			THEN
				SET V_TABLE_NAME = I_DB ||'.'|| I_TBL;
			ELSE
				SET V_TABLE_NAME = I_TBL;
			END IF;
		END IF;
		
		SET v_cnt_query = 'SEL COUNT (1) (float) FROM ' ||V_TABLE_NAME ||';' ;
		PREPARE S1 FROM v_cnt_query;
		OPEN C1;
		FETCH C1 INTO v_cnt_result;
		CLOSE C1;
		SET O_CNT = v_cnt_result;
		SET O_RETURN_CODE = 0;
		SET O_RETURN_MSG = 'Process Completed Successfully';
	END;
END;
