--update GDEV1_ETL.SOURCE_SYSTEMS set LOADING_MODE = 'OFFLINE';
     
     
call GDEV1_ETL.STG_LOADING
	    (
	    NULL -- i_SOURCE_NAME
	    ,NULL--IN 		I_PROCESSNAME  			VARCHAR(1000),
	    ,202304251635053911--IN 		I_RUN_ID 				BIGINT,
	    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
	    ,NULL	-- IN 		I_RELOAD,	
	    ,NULL	-- IN 		I_ALL_BATCHES,	
	    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
	    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
	    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
	    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
	    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
	    ,r
	    );
	    
call GDEV1_ETL.bkey_LOADING
    (
    NULL -- i_SOURCE_NAME
    ,NULL--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,NULL -- IN 		i_TABLE_NAME  		VARCHAR(200),
    ,202304251635053911--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    ,r
    );

call GDEV1_ETL.SRCI_LOADING
    (
    NULL -- i_SOURCE_NAME
    ,NULL--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,202304251635053911--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),	
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    ,r
    );
  
 call GDEV1_ETL.EDW_LOADING
    (
    NULL -- i_SOURCE_NAME
    ,NULL--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,'CORE' -- IN 		i_LAYER_NAME  		VARCHAR(200),
    ,NULL -- IN 		i_TABLE_NAME  		VARCHAR(200),
    ,202304251635053911--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    ,r);
    --------------