--HISTORY TXF_CORE_L1_PRTY_IDNTFTN_L0_CSO_NEW_PERSON_CSO_NUMBER
--INSERT SHOW VIEW GDEV1V_INP.TXF_CORE_L1_LOCTR_L0_CSO_NEW_ADDRESS

-- BKEY BK_17_CSO_GOVERNORATE_SK_GOVERNORATE_CSO_CODE_4

DELETE FROM GDEV1_ETL.EXEC_SCRIPT_LOGS  ;

SELECT *
  FROM GDEV1_ETL.EXEC_SCRIPT_LOGS x
where RUN_ID = 202304251635053911


order by START_TIMESTAMP desc;


SELECT *
  FROM GDEV1_ETL.EXEC_PROCESS_LOGS x
 WHERE 1=1
AND RUN_ID = 202304251635053906

order by START_TIMESTAMP desc;





select * from GDEV1_ETL.process where main_table_name in ('CSO_ADDRESS', 'CSO_NEW_PERSON') order by PROCESS_TYPE,main_table_name, APPLY_TYPE;

show view  GDEV1V_STG_ONLINE.CSO_NEW_PERSON;
DELETE FROM GDEV1T_STG.CSO_NEW_PERSON;



	update GDEV1_ETL.SOURCE_SYSTEM_TABLES set IS_TARANSACTIOANL = 0;
	call GDEV1_ETL.STG_LOADING
	    (
	    'DIRECT SALES' -- i_SOURCE_NAME
	    ,NULL--IN 		I_PROCESSNAME  			VARCHAR(1000),
	    ,202304251635053911--IN 		I_RUN_ID 				BIGINT,
	    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
	    ,NULL	-- IN 		I_RELOAD,	
	    ,NULL	-- IN 		I_ALL_BATCHES,	
	    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
	    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
	    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
	    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
	    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
	    ,r
	    );
call GDEV1_ETL.bkey_LOADING
    (
    NULL -- i_SOURCE_NAME
    ,NULL--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,NULL -- IN 		i_TABLE_NAME  		VARCHAR(200),
    ,202304251635053906--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    ,r
    );

call GDEV1_ETL.SRCI_LOADING
    (
    NULL -- i_SOURCE_NAME
    ,NULL--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,202304251635053906--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),	
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    ,r
    );
  
 call GDEV1_ETL.EDW_LOADING
    (
    NULL -- i_SOURCE_NAME
    ,NULL--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,'CORE' -- IN 		i_LAYER_NAME  		VARCHAR(200),
    ,NULL -- IN 		i_TABLE_NAME  		VARCHAR(200),
    ,202304251635053906--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    ,r);
    --------------


    
    
