--HISTORY TXF_CORE_L1_PRTY_IDNTFTN_L0_CSO_NEW_PERSON_CSO_NUMBER
--INSERT SHOW VIEW GDEV1V_INP.TXF_CORE_L1_LOCTR_L0_CSO_NEW_ADDRESS

-- BKEY BK_17_CSO_GOVERNORATE_SK_GOVERNORATE_CSO_CODE_4

DELETE FROM GDEV1_ETL.EXEC_LOGS  ;

SELECT *
  FROM GDEV1_ETL.EXEC_LOGS x
 WHERE 1=1
-- AND RUN_ID = 202304190625396600
order by START_TIMESTAMP desc;
    
    select * from GDEV1V_STG_ONLINE.CSO_NEW_PERSON;
select * from GDEV1_ETL.process where main_table_name in ('CSO_ADDRESS', 'CSO_NEW_PERSON') order by PROCESS_TYPE,main_table_name, APPLY_TYPE;
select * from GDEV1V_INP.TXF_CORE_L1_PRTY_LOCTR_L0_CSO_NEW_ADDRESS_IN;
select * from GDEV1T_BASE.PRTY_LOCTR  ;

show view GDEV1V_INP.TXF_CORE_L1_PRTY_LOCTR_L0_CSO_NEW_ADDRESS_IN;


call GDEV1_ETL.STG_PROCESS_LOADING
    (
    'CSO_NEW_PERSON'--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,NULL--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    , 1	-- IN 		I_REFRESH_LOADS,	
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    );
 
    call GDEV1_ETL.STG_PROCESS_LOADING
    (
    'CSO_ADDRESS'--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,NULL--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    , 1	-- IN 		I_REFRESH_LOADS,
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    );
    


    --BK_17_CSO_ADDRESS_SK_POLICE_STATION_ID_14
	--BK_17_CSO_ADDRESS_SK_ADDRESS_3
	--BK_1_CSO_NEW_PERSON_SK_NATIONAL_ID_1
	--BK_17_CSO_NEW_PERSON_SK_NID_BIRTH_GOV_4

 
call GDEV1_ETL.BKEY_PROCESS_LOADING
(
	NULL	--IN i_LOAD_ID 			VARCHAR(100), 
	,NULL--IN i_run_id 			BIGINT,
	,'BK_17_CSO_ADDRESS_SK_POLICE_STATION_ID_14' --i_PROCESS_NAME  		VARCHAR(500), 
	,x	--OUT RETURN_CODE    		INTEGER,
	,y 	--OUT RETURN_MSG  		VARCHAR(1000),
	,z	--OUT ROWS_COUNT_VALUE	INTEGER
);

 
call GDEV1_ETL.BKEY_PROCESS_LOADING
(
	NULL	--IN i_LOAD_ID 			VARCHAR(100), 
	,NULL--IN i_run_id 			BIGINT,
	,'BK_17_CSO_ADDRESS_SK_ADDRESS_3' --i_PROCESS_NAME  		VARCHAR(500), 
	,x	--OUT RETURN_CODE    		INTEGER,
	,y 	--OUT RETURN_MSG  		VARCHAR(1000),
	,z	--OUT ROWS_COUNT_VALUE	INTEGER
);
    
call GDEV1_ETL.BKEY_PROCESS_LOADING
(
	NULL	--IN i_LOAD_ID 			VARCHAR(100), 
	,NULL--IN i_run_id 			BIGINT,
	,'BK_1_CSO_NEW_PERSON_SK_NATIONAL_ID_1' --i_PROCESS_NAME  		VARCHAR(500), 
	,x	--OUT RETURN_CODE    		INTEGER,
	,y 	--OUT RETURN_MSG  		VARCHAR(1000),
	,z	--OUT ROWS_COUNT_VALUE	INTEGER
);

call GDEV1_ETL.BKEY_PROCESS_LOADING
(
	NULL	--IN i_LOAD_ID 			VARCHAR(100), 
	,NULL--IN i_run_id 			BIGINT,
	,'BK_17_CSO_NEW_PERSON_SK_NID_BIRTH_GOV_4' --i_PROCESS_NAME  		VARCHAR(500), 
	,x	--OUT RETURN_CODE    		INTEGER,
	,y 	--OUT RETURN_MSG  		VARCHAR(1000),
	,z	--OUT ROWS_COUNT_VALUE	INTEGER
);

call GDEV1_ETL.SRCI_PROCESS_LOADING
    (
    'CSO_ADDRESS'--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,NULL--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    );
    
    call GDEV1_ETL.SRCI_PROCESS_LOADING
    (
    'CSO_NEW_PERSON'--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,NULL--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    );
    
call GDEV1_ETL.TXF_PROCESS_LOADING
    (
    'TXF_CORE_L1_PRTY_LOCTR_L0_CSO_NEW_ADDRESS'--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,NULL-- IN 		I_APPLY_TYPE  			VARCHAR(500),
    ,NULL--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    );
  call GDEV1_ETL.TXF_PROCESS_LOADING
    (
    'TXF_CORE_L1_INDIV_NAME_L0_CSO_NEW_PERSON_IN'--IN 		I_PROCESSNAME  			VARCHAR(1000),
    ,NULL-- IN 		I_APPLY_TYPE  			VARCHAR(500),
    ,NULL--IN 		I_RUN_ID 				BIGINT,
    ,NULL--IN		I_LOAD_ID				VARCHAR(500),
    ,x --OUT  	O_ROWS_INSERTED_COUNT	FLOAT,
    ,x1 --OUT  	O_ROWS_UPDATED_COUNT	FLOAT,
    ,x2 --OUT  	O_ROWS_DELETED_COUNT	FLOAT,
    ,x3 --OUT  	O_RETURN_CODE  			INTEGER,
    ,x4 --OUT  	O_RETURN_MSG 			VARCHAR(5000)
    );  
    

    
    
