
SELECT * FROM GDEV1T_STG.DBSS_CRM_TRANSACTIONSTRANSACTION; 
SELECT * FROM GDEV1T_STG.JSON_SALES_STG;
SELECT * FROM GDEV1T_STG.DBSS_CRM_TRANSACTIONSPAYMENT;

SELECT * FROM GDEV1T_STG.DBSS_OM_ORDEREDCONTRACTSORDEREDCONTRACT;
SELECT * FROM GDEV1T_STG.DBSS_OM_ORDEREDCONTRACTSORDEREDDEVICE;
SELECT * FROM GDEV1T_STG.DBSS_OM_ORDEREDCONTRACTSORDEREDSIMCARD;
SELECT * FROM GDEV1T_STG.DBSS_PC_PRODUCTSITEMVARIANT; -- LOOKUP FOR DEVICES


below is relation between tables and the tables details, I want sum queries that show some metrics and insights

Relations:
JSON_SALES_STG.TRANSACTION_ID = DBSS_CRM_TRANSACTIONSTRANSACTION.id
DBSS_CRM_TRANSACTIONSPAYMENT.TRANSACTION_ID = DBSS_CRM_TRANSACTIONSTRANSACTION.id
DBSS_OM_ORDEREDCONTRACTSORDEREDCONTRACT.CONFIRMATION_CODE = JSON_SALES_STG.CONFIRMATION_CODE

DBSS_OM_ORDEREDCONTRACTSORDEREDDEVICE.CONTRACT_ID = DBSS_OM_ORDEREDCONTRACTSORDEREDCONTRACT.id
DBSS_OM_ORDEREDCONTRACTSORDEREDDEVICE.TYPE_ID = DBSS_PC_PRODUCTSITEMVARIANT.id
DBSS_OM_ORDEREDCONTRACTSORDEREDSIMCARD.CONTRACT_ID = DBSS_OM_ORDEREDCONTRACTSORDEREDCONTRACT.id
 	
Tables:
CREATE multiset TABLE GDEV1T_STG.DBSS_CRM_TRANSACTIONSTRANSACTION
    ,FALLBACK
    ,NO BEFORE JOURNAL
    ,NO AFTER JOURNAL
    ,CHECKSUM = DEFAULT
    ,DEFAULT MERGEBLOCKRATIO
(
	 CDC_CODE  BYTEINT   
 	,CUSTOMER_INFORMATION  VARCHAR(32) CHARACTER SET latin not CASESPECIFIC 
 	,DEALERS_CODE  VARCHAR(32) CHARACTER SET latin not CASESPECIFIC 
 	,FILE_ARRIVING_DATE  DATE   
 	,ID  INTEGER   not null
 	,INVOICE_INFORMATION  VARCHAR(200) CHARACTER SET latin not CASESPECIFIC 
 	,INVOICE_TYPE  SMALLINT   
 	,LAST_MODIFIED  TIMESTAMP(0)   
 	,SALESMEN_CODE  VARCHAR(32) CHARACTER SET latin not CASESPECIFIC 
 	,TRANSACTION_DATE  TIMESTAMP(0)   
 	,TRANSACTION_IDENTIFIER  VARCHAR(32) CHARACTER SET latin not CASESPECIFIC 
 	,TRANSACTION_TYPE  SMALLINT   
 	,MODIFICATION_TYPE  CHAR(1) CHARACTER SET latin not CASESPECIFIC not null
 	,LOAD_ID  VARCHAR(60) CHARACTER SET latin not CASESPECIFIC not null
 	,BATCH_ID  INT   not null
 	,REF_KEY  BIGINT   not null
 	,INS_DTTM  TIMESTAMP(6)   not null
 	,UPD_DTTM  TIMESTAMP(6)   
 )
unique PRIMARY INDEX ( ID );


CREATE multiset TABLE GDEV1T_STG.JSON_SALES_STG
    ,FALLBACK
    ,NO BEFORE JOURNAL
    ,NO AFTER JOURNAL
    ,CHECKSUM = DEFAULT
    ,DEFAULT MERGEBLOCKRATIO
(
	 AMOUNT_BEFORE_STAMP_DUTY  DECIMAL(16,2)   
 	,AMOUNT_WITHOUT_VAT  DECIMAL(16,2)   
 	,CDC_CODE  BYTEINT   
 	,CONFIRMATION_CODE  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,DEALERS_CODE  VARCHAR(32) CHARACTER SET latin not CASESPECIFIC 
 	,FILE_ARRIVING_DATE  DATE   
 	,ID  INTEGER   not null
 	,INVOICE_DATE_TIME  TIMESTAMP(0)   
 	,INVOICE_INFORMATION  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,INVOICE_NUMBER  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,LAST_MODIFIED  TIMESTAMP(0)   
 	,SALESMAN_CODE  VARCHAR(32) CHARACTER SET latin not CASESPECIFIC 
 	,STAMP_DUTY  DECIMAL(16,2)   
 	,TOTAL_AMOUNT  DECIMAL(16,2)   
 	,TRANSACTION_ID  INTEGER   --> = DBSS_CRM_TRANSACTIONSTRANSACTION.id
 	,VAT  DECIMAL(16,2)   
 	,PROVINCE  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,SHOP_ADDRESS  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,PAYMENT_MODES  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,NAME  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,TITL  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,MSISDN  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,FISCAL_CODE  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,NOTES  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,INVOICE_TEMPLATE  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,SHOP_NAME  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,PD_VALUE_ADDED_TAX  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,PD_STAMP_DUTY  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,PD_TOTAL_AMOUNT_TO_BE_PAID  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,PD_SETTLEMENT_DISCOUNT  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,PD_TOTAL_PRICE_INCLUDING_TAX  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,PD_TOTAL_AMOUNT_BEFORE_TAX  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,PD_TOTAL_AMOUNT_WHEN_PAYMENT_IN_CASH  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,ICC  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,SHOP_ID  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,POSTAL_CODE  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,ADDRESS  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,SALESMEN_CODE  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,TITLE_NAME  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,ORDER_ID  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,CITY  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,SEQUENCE_NUMBER  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,AMOUNT_BEFORE_TAX  DECIMAL(16,2)   
 	,UNIT_PRICE_WITHOUT_VAT  DECIMAL(16,2)   
 	,PAYNOW  DECIMAL(16,2)   
 	,DESCRIPTION  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,PRODUCT_CODE  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,QUANTITY  INTEGER   
 	,DISCOUNT  INTEGER   
 	,MODIFICATION_TYPE  CHAR(1) CHARACTER SET latin not CASESPECIFIC not null
 	,LOAD_ID  VARCHAR(60) CHARACTER SET latin not CASESPECIFIC not null
 	,BATCH_ID  INT   not null
 	,REF_KEY  BIGINT   not null
 	,INS_DTTM  TIMESTAMP(6)   not null
 	,UPD_DTTM  TIMESTAMP(6)   
 )
unique PRIMARY INDEX ( ID );

CREATE multiset TABLE GDEV1T_STG.DBSS_CRM_TRANSACTIONSPAYMENT
    ,FALLBACK
    ,NO BEFORE JOURNAL
    ,NO AFTER JOURNAL
    ,CHECKSUM = DEFAULT
    ,DEFAULT MERGEBLOCKRATIO
(
	 BEFORE_VAT_AMOUNT  DECIMAL(32,6)   
 	,CDC_CODE  BYTEINT   
 	,CHEQUE_NUMBER  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,FILE_ARRIVING_DATE  DATE   
 	,ID  INTEGER   not null
 	,LAST_MODIFIED  TIMESTAMP(0)   
 	,PAID_AMOUNT  DECIMAL(32,6)   
 	,PAYMENT_MODE  SMALLINT   
 	,SETTLEMENT_DISCOUNT  DECIMAL(32,6)   
 	,TAX_PAYMENT  DECIMAL(32,6)   
 	,TOTAL_PAID  DECIMAL(32,6)   
 	,TRANSACTION_ID  INTEGER   --> = DBSS_CRM_TRANSACTIONSTRANSACTION.id
 	,VAT  DECIMAL(32,6)   
 	,MODIFICATION_TYPE  CHAR(1) CHARACTER SET latin not CASESPECIFIC not null
 	,LOAD_ID  VARCHAR(60) CHARACTER SET latin not CASESPECIFIC not null
 	,BATCH_ID  INT   not null
 	,REF_KEY  BIGINT   not null
 	,INS_DTTM  TIMESTAMP(6)   not null
 	,UPD_DTTM  TIMESTAMP(6)   
 )
unique PRIMARY INDEX ( ID );


CREATE multiset TABLE GDEV1T_STG.DBSS_OM_ORDEREDCONTRACTSORDEREDCONTRACT
    ,FALLBACK
    ,NO BEFORE JOURNAL
    ,NO AFTER JOURNAL
    ,CHECKSUM = DEFAULT
    ,DEFAULT MERGEBLOCKRATIO
(
	 ID  INTEGER   not null
 	,CUSTOMER_ID  INTEGER   
 	,CONFIRMATION_CODE  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC --> = JSON_SALES_STG.CONFIRMATION_CODE
 	,CREATED_AT  TIMESTAMP(0)   
 	,SALES_INFO_ID  INTEGER   
 	,FILE_ARRIVING_DATE  DATE   
 	,STATUS  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,DELIVERY_TYPE  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,LAST_MODIFIED  TIMESTAMP(0)   
 	,BRAND  INTEGER   
 	,ORDERED_AT  TIMESTAMP(0)   
 	,DELIVERY_ADDRESS_ID  INTEGER   
 	,OFFER  VARCHAR(1024) CHARACTER SET latin not CASESPECIFIC 
 	,CORRECTION_FOR  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,DEVICES_RETURNED_AT  TIMESTAMP(0)   
 	,PURCHASE_ORDER_ID  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,CDC_CODE  BYTEINT   
 	,MODIFICATION_TYPE  CHAR(1) CHARACTER SET latin not CASESPECIFIC not null
 	,LOAD_ID  VARCHAR(60) CHARACTER SET latin not CASESPECIFIC not null
 	,BATCH_ID  INT   not null
 	,REF_KEY  BIGINT   not null
 	,INS_DTTM  TIMESTAMP(6)   not null
 	,UPD_DTTM  TIMESTAMP(6)   
 )
unique PRIMARY INDEX ( ID );

CREATE multiset TABLE GDEV1T_STG.DBSS_PC_PRODUCTSITEMVARIANT
    ,FALLBACK
    ,NO BEFORE JOURNAL
    ,NO AFTER JOURNAL
    ,CHECKSUM = DEFAULT
    ,DEFAULT MERGEBLOCKRATIO
(
	 CART_IMAGE  VARCHAR(100) CHARACTER SET latin not CASESPECIFIC 
 	,CODE  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,COLOR_ID  INTEGER   
 	,COVER_IMAGE  VARCHAR(100) CHARACTER SET latin not CASESPECIFIC 
 	,DISPLAY_ORDER  INTEGER   
 	,FILE_ARRIVING_DATE  DATE   
 	,ID  INTEGER   not null
 	,ITEM_MODEL_ID  INTEGER   
 	,NAME_PRODUCTSITEMVARIANT  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,OUT_OF_STOCK  INTEGER   
 	,OUT_OF_STOCK_ACTION  VARCHAR(64) CHARACTER SET latin not CASESPECIFIC 
 	,STATUS  INTEGER   
 	,MODIFICATION_TYPE  CHAR(1) CHARACTER SET latin not CASESPECIFIC not null
 	,LOAD_ID  VARCHAR(60) CHARACTER SET latin not CASESPECIFIC not null
 	,BATCH_ID  INT   not null
 	,REF_KEY  BIGINT   not null
 	,INS_DTTM  TIMESTAMP(6)   not null
 	,UPD_DTTM  TIMESTAMP(6)   
 )
unique PRIMARY INDEX ( ID );

CREATE multiset TABLE GDEV1T_STG.DBSS_OM_ORDEREDCONTRACTSORDEREDDEVICE
    ,FALLBACK
    ,NO BEFORE JOURNAL
    ,NO AFTER JOURNAL
    ,CHECKSUM = DEFAULT
    ,DEFAULT MERGEBLOCKRATIO
(
	 ID  INTEGER   not null
 	,CONTRACT_ID  INTEGER   --> = DBSS_OM_ORDEREDCONTRACTSORDEREDCONTRACT.id
 	,TYPE_ID  INTEGER   --> = DBSS_PC_PRODUCTSITEMVARIANT.id
 	,LAST_MODIFIED  TIMESTAMP(0)   
 	,PRICE  DECIMAL(16,6)   
 	,ARTICLE_ID  VARCHAR(4096) CHARACTER SET latin not CASESPECIFIC 
 	,DATA  VARCHAR(5500) CHARACTER SET latin not CASESPECIFIC 
 	,QUANTITY  INTEGER   
 	,CDC_CODE  BYTEINT   
 	,FILE_ARRIVING_DATE  DATE   
 	,MODIFICATION_TYPE  CHAR(1) CHARACTER SET latin not CASESPECIFIC not null
 	,LOAD_ID  VARCHAR(60) CHARACTER SET latin not CASESPECIFIC not null
 	,BATCH_ID  INT   not null
 	,REF_KEY  BIGINT   not null
 	,INS_DTTM  TIMESTAMP(6)   not null
 	,UPD_DTTM  TIMESTAMP(6)   
 )
unique PRIMARY INDEX ( ID );

CREATE multiset TABLE GDEV1T_STG.DBSS_OM_ORDEREDCONTRACTSORDEREDSIMCARD
    ,FALLBACK
    ,NO BEFORE JOURNAL
    ,NO AFTER JOURNAL
    ,CHECKSUM = DEFAULT
    ,DEFAULT MERGEBLOCKRATIO
(
	 ID  INTEGER   not null
 	,PRICE  DECIMAL(16,6)   
 	,CONTRACT_ID  INTEGER   -- = DBSS_OM_ORDEREDCONTRACTSORDEREDCONTRACT.id
 	,LAST_MODIFIED  TIMESTAMP(0)   
 	,IMSI  VARCHAR(129) CHARACTER SET latin not CASESPECIFIC 
 	,ITEM  VARCHAR(100) CHARACTER SET latin not CASESPECIFIC 
 	,ARTICLE_ID  VARCHAR(128) CHARACTER SET latin not CASESPECIFIC 
 	,MODIFICATION_TYPE  CHAR(1) CHARACTER SET latin not CASESPECIFIC not null
 	,LOAD_ID  VARCHAR(60) CHARACTER SET latin not CASESPECIFIC not null
 	,BATCH_ID  INT   not null
 	,REF_KEY  BIGINT   not null
 	,INS_DTTM  TIMESTAMP(6)   not null
 	,UPD_DTTM  TIMESTAMP(6)   
 )
unique PRIMARY INDEX ( ID );


